name: "assets / r2 / qa"

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - run: pnpm dlx wrangler r2 object put ikea-static-qa/favicon.ico --file workers/assets-sync/public/favicon.ico
